### ISSUE TITLE
rename LD variables to PC variables

### ISSUE THREAD

**Issue by jrdupuis** [popphylotools/mvMapper#37]
To be more in line with the original DAPC publication, we should rename the variables that get called LD1-LD8 to PC1-PC8. Those coordinate systems are the principal components, so "PC" would be more appropriate.

**Comment by Woods26** [comment]
alright, I can handle "LD" specific code on the mvMapper side, but these names come from the column headers, so this must be addressed in the companion R function in adegenet as well.

**Comment by jrdupuis** [comment]
Yeah, the R input function adds PC for all analysis types, so that should be good. 

Line 103 here: https://github.com/thibautjombart/adegenet/blob/master/R/export_to_webapp.R
