### ISSUE TITLE
rename webapp_input.csv

### ISSUE THREAD

**Issue by jrdupuis** [popphylotools/mvMapper#39]
How about renaming the main input file? Maybe to mapper_input.csv or dapcmapper_input.csv?

**Comment by Woods26** [comment]
@jrdupuis 

mvMapper_input.csv?
mvmapper_input.csv?

**Comment by jrdupuis** [comment]
This file name will be specified by the user when using the new data prep function in R, so it can be whatever. I'd say, let's make it `mvmapper_input.csv`

**Comment by Woods26** [comment]
righto, thanks
