### ISSUE TITLE
hovering over tools displaying blank white box, no text

### ISSUE THREAD

**Issue by jrdupuis** [popphylotools/mvMapper#40]
tested on firefox and chrome...not sure if this is a browser thing or a bokeh thing, but I'm expecting the words "pan", "box select", "mouse-wheel", etc., or something along those lines.

**Comment by Woods26** [comment]
alright, I'll see if I can reproduce this

**Comment by Woods26** [comment]
yeah, I'm seeing the same thing. I thought they used to be there... but all the old versions seem to be doing this too. I'm going to dig into this a bit more.
