### ISSUE TITLE
Display all web_app input data in metadata panel when selecting points?

### ISSUE THREAD

**Issue by jrdupuis** [popphylotools/mvMapper#41]
So there's two different ways that metadata are displayed in the lower panel when points are selected. If it's a DAPC, only the key, grp, assign, posteriors, and additional columns are shown. But if you create your own webapp_input.csv file with non-DAPC-named columns, then everything shows up. I wonder if we should show all the data for DAPC instances (i.e. include the DF1-DFX in that panel). Thoughts? @smg283?

It would make it a bit more consistent, although then more is shown for a dapc analysis. I could see some cases where having all the data shown down there would be nice--maybe you would notice other trends for certain populations, etc.

Anyhow, just a thought.

**Comment by Woods26** [comment]
I simply removed "LD*" named columns from displaying in the summary panel, they should still be in the downloaded dataset.

It would be easy to re-add them, I just thought having them sort of cluttered the display. Maybe if we set up the input file so they are the last columns, we can have them without crowding out the display.
