### ISSUE TITLE
Clean up old data prep (from DAPC) code?

### ISSUE THREAD

**Issue by jrdupuis** [popphylotools/mvMapper#44]
With the data prep now done in R, is the best course of action just to hash out the code that used to do data prep from DAPC? Or is it just as easy as removing the dataprep.py script?

If we do the former, maybe we also just add a comment that that section of hashed out code was for a prelim version that automated input from DAPC only, in case anyone wanted to unhash it and use it (why someone would want to do that I don't know).

**Comment by Woods26** [comment]
I'll clean it up. we can always go to the old release if we want the code back.
