### ISSUE TITLE
Update defaults for each pulldown menu

### ISSUE THREAD

**Issue by jrdupuis** [popphylotools/mvMapper#45]
Now that everything will follow the same format, can we update the defaults for what is shown in the "X axis", "Y axis", "color by", "size by" pulldowns?

How it's written now, the new defaults should be:
X-axis: PC1
Y-axis: PC2
color: grp
size: support

"support" will still be a DAPC-only thing, but that's fine in my mind. I bring it up in the manuscript as an option for DAPC only.

**Comment by Woods26** [comment]
I think this should be set in the config file (re: #29) rather than having hard coded defaults. I'll keep this here to track the desired content of that file.

**Comment by thibautjombart** [comment]
Note that `grp` may also be absent, as we now allow other methods than DAPC. As far as I can tell, the only fields that will be always there are:
- `key`: unique individual ID
- `PC1`: 1st principal component
- `lat`: latitude
- `lon`: longitude

**Comment by jrdupuis** [comment]
Yeah, that sounds good @thibautjombart 
The defaults aren't that important, since you can always just switch whats displayed when you start up an instance of the app. I also make a note of using "grp" to refer to population in the manuscript.
